slam_toolbox:
  ros__parameters:

    # Frames
    map_frame: map
    odom_frame: map        # PX4 does NOT give wheel odom
    base_frame: base_link

    # Laser
    scan_topic: /world/custom_indoor_lab/model/x500_lidar_2d_0/link/link/sensor/lidar_2d_v2/scan

    # Mode
    mode: mapping

    # Map parameters
    resolution: 0.05
    max_laser_range: 30.0

    # Performance / timing
    transform_timeout: 0.2
    minimum_time_interval: 0.1
    map_update_interval: 1.0

    # Loop closure
    do_loop_closing: true
